# This GitHub Actions workflow is named "black-formatter" and is triggered on push and pull request events.
# It has read permissions for repository contents.
#
# The workflow defines a single job named "black-linter" that runs on the latest Ubuntu runner.
#
# Steps:
# 1. Harden Runner:
#    - Uses the "step-security/harden-runner" action (specific commit) to enhance security.
#    - Disables sudo, blocks egress traffic, and allows specific endpoints (files.pythonhosted.org, github.com, pypi.org).
#
# 2. Checkout Code:
#    - Uses the "actions/checkout" action (specific commit) to check out the repository code.
#
# 3. Run Black Formatter:
#    - Uses the "psf/black" action (specific commit) to run the Black code formatter on the repository.

name: black-formatter

# Define the events that trigger this workflow
on:
  push: # Trigger on push events
  pull_request: # Trigger on pull request events

# Define permissions required for the workflow
permissions:
  contents: read # Required to fetch repository contents

concurrency:
  group: black-formatter-${{ github.ref }} # Group for concurrency control
  cancel-in-progress: false # Do not cancel in-progress jobs

jobs:
  black-linter:
    # Specify the runner to use (ubuntu-latest)
    runs-on: ubuntu-latest

    steps:
      # Step to harden the runner for security purposes
      - name: Harden Runner
        uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
        with:
          disable-sudo: true # Disable sudo to prevent privilege escalation
          egress-policy: block # Block all egress traffic
          allowed-endpoints: > # Allow specific endpoints for necessary traffic
            files.pythonhosted.org:443
            github.com:443
            pypi.org:443

      # Step to checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      # Step to run the Black code formatter
      - name: Run Black Formatter
        uses: psf/black@6305bf1ae645ab7541be4f5028a86239316178eb # stable
