name: Greetings

# Define the events that trigger this workflow
on:
  pull_request_target: # Trigger on pull request events targeting the repository
  issues: # Trigger on issue events

# Define permissions required for the workflow
permissions:
  contents: read # Required to fetch repository contents

concurrency:
  group: greetings-${{ github.ref }}
  cancel-in-progress: false

jobs:
  greeting:
    # Specify the runner to use (ubuntu-latest)
    runs-on: ubuntu-latest

    # Define permissions specific to the job
    permissions:
      issues: write # Required to write comments on issues
      pull-requests: write # Required to write comments on pull requests

    steps:
      # Step to harden the runner for security purposes
      - name: Harden Runner
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit # Set egress policy to audit

      # Step to send a greeting message for issues and pull requests
      - name: First Interaction
        uses: actions/first-interaction@1c4688942c71f71d4f5502a26ea67c331730fa4d # v3.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }} # Use the repository token for authentication
          issue-message: "Greetings, thanks for opening an issue, I'll look when I can." # Message for new issues
          pr-message: "Greetings, thanks for opening a pull request, I'll look when I can." # Message for new pull requests
